filter:
    paths: [src/*]
    excluded_paths: [tests/*]
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    php_sim: true
    php_changetracking: true
    php_cs_fixer: 
        config:
            level: all
    php_analyzer: true
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc: true
    php_cpd: true
